services:
  postgres:
    image: postgres:latest
    container_name: postgresDb
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
  backend:
    build: ./Be
    container_name: flask_backend
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLASK_APP=Server.py
      - FERKEY=U6vDZB8WeULHutdkjGT1yQn9cIjE6jWb91YJ3dkQQwE= # Thêm dòng này
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/DoAnTotNghiep
    ports:
      - "5000:5000"
    volumes:
      - ./Be:/app
    working_dir: /app
    command: sh -c "flask db upgrade && python Server.py"
