"""empty message

Revision ID: 33b6fceead86
Revises: d1c7478de651
Create Date: 2025-05-01 14:14:46.842342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b6fceead86'
down_revision = 'd1c7478de651'
branch_labels = None
depends_on = None


def upgrade():
    # ...existing code...
    op.alter_column(
        'letterOvertime',
        'create_at',
        existing_type=sa.DateTime(),
        type_=sa.TIMESTAMP(timezone=False),
        postgresql_using="create_at::timestamp without time zone"
    )
    # ...existing code...

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letterOvertime', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
