"""update type total overtime

Revision ID: 36013338695d
Revises: b43d54d520b0
Create Date: 2025-05-03 03:56:53.221518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36013338695d'
down_revision = 'b43d54d520b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('total_overtime',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('total_overtime',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
