"""update id type and fix some code

Revision ID: 3cc0558fbe58
Revises: 36013338695d
Create Date: 2025-05-05 19:40:06.823117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc0558fbe58'
down_revision = '36013338695d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dayOff', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dayOff', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
