"""delete early_in and late_out

Revision ID: 86c148224ad4
Revises: 8892eb238e0f
Create Date: 2025-05-03 03:24:44.914544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c148224ad4'
down_revision = '8892eb238e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('late_in')
        batch_op.drop_column('early_out')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_out', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('late_in', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
