"""delete field status_attendance

Revision ID: 8892eb238e0f
Revises: d7befff4ab64
Create Date: 2025-05-03 03:21:06.938499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8892eb238e0f'
down_revision = 'd7befff4ab64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('status_attendance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_attendance', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
