"""change type payroll

Revision ID: 9c64f6f5d05f
Revises: 3cc0558fbe58
Create Date: 2025-05-06 11:18:55.989724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c64f6f5d05f'
down_revision = '3cc0558fbe58'
branch_labels = None
depends_on = None


def upgrade():
    
    op.drop_constraint('payrollAllowance_payroll_id_fkey', 'payrollAllowance', type_='foreignkey')
    op.drop_constraint('payrollDeducation_payroll_id_fkey', 'payrollDeducation', type_='foreignkey')
    op.drop_constraint('payrollAllowance_allowance_id_fkey', 'payrollAllowance', type_='foreignkey')
    op.drop_constraint('payrollDeducation_deducation_id_fkey', 'payrollDeducation', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.DATE(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('payroll_id_seq'::regclass)"))
        batch_op.drop_column('moth')
    
    # Thay đổi kiểu dữ liệu của id trong bảng allowance
    with op.batch_alter_table('allowance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # Thay đổi kiểu dữ liệu của id trong bảng deducation
    with op.batch_alter_table('deducation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # 3. Thay đổi kiểu dữ liệu trong các bảng trung gian
    with op.batch_alter_table('payrollAllowance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('payroll_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('allowance_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('payrollDeducation', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('payroll_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('deducation_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # 4. Tạo lại tất cả các ràng buộc khóa ngoại
    op.create_foreign_key('payrollAllowance_payroll_id_fkey', 
                         'payrollAllowance', 'payroll', 
                         ['payroll_id'], ['id'])
    op.create_foreign_key('payrollDeducation_payroll_id_fkey', 
                         'payrollDeducation', 'payroll', 
                         ['payroll_id'], ['id'])
    op.create_foreign_key('payrollAllowance_allowance_id_fkey', 
                         'payrollAllowance', 'allowance', 
                         ['allowance_id'], ['id'])
    op.create_foreign_key('payrollDeducation_deducation_id_fkey', 
                         'payrollDeducation', 'deducation', 
                         ['deducation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrollDeducation', schema=None) as batch_op:
        batch_op.alter_column('deducation_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('payroll_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('payrollAllowance', schema=None) as batch_op:
        batch_op.alter_column('allowance_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('payroll_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moth', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('payroll_id_seq'::regclass)"))
        batch_op.drop_column('month')

    # ### end Alembic commands ###
