"""empty message

Revision ID: d1c7478de651
Revises: b5c734ee4815
Create Date: 2025-05-01 14:11:53.394017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c7478de651'
down_revision = 'b5c734ee4815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letterOvertime', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('letterOvertime', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
