"""update key

Revision ID: ddd188f30867
Revises: dd381ce45cd2
Create Date: 2025-04-02 17:02:19.255058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd188f30867'
down_revision = 'dd381ce45cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('account_empployee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['id'], ['id'])
        batch_op.drop_column('empployee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empployee_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('account_empployee_id_fkey', 'employee', ['empployee_id'], ['id'])

    # ### end Alembic commands ###
